spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: chatDB
    application:
      name: fe-core-challenge
server:
  port: 8888

dockerspring:
  data:
    mongodb:
      uri: mongodb://mongo_db:27017/chatDB
